const Tdata = [
  {
    id: 1,
    desc1:"Great value!",
    desc2: "It's a good website for getting the best rates for hotels. I got a really good deal for a twin-bed room which was perfect for my trip as I was on a tight budget.",
    name: "WONG LO KAT",
    profile: "/images/profile/profile1-anonymous.png",
    post1: "Rating: 5/5",
    post2: "Date reviewed: 06-11-2023",
    post3: "𖡡 Malaysia",
  },
  {
    id: 2,
    desc1: "Helpful customer support",
    desc2: "I encountered an issue with my booking, but the customer service team was incredibly helpful and resolved it promptly. They were courteous and professional throughout the process, ensuring that my stay was not disrupted. Kudos to the team for their outstanding service!",
    name: "YUSUF TAIYOOB",
    profile: "/images/profile/profile1-anonymous.png",
    post1: "Rating: 5/5",
    post2: "Date reviewed: 21-12-2023",
    post3: "𖡡 Malaysia",
  },
  {
    id: 3,
    desc1: "Great payment system",
    desc2: "This site has transparent pricing since I didn't see any hidden fees at checkout. Also, they support most of the major payment options.",
    name: "REDZUAWAN BIN ISMAIL",
    profile: "/images/profile/profile1-anonymous.png",
    post1: "Rating: 5/5",
    post2: "Date reviewed: 03-01-2024",
    post3: "𖡡 Malaysia",
  },
  {
    id: 4,
    desc1: "The site is mobile friendly",
    desc2: "I made my booking through mobile phone and it was really simple to navigate the website! I will definitely book hotels from this website again.",
    name: "EMILY ROSE",
    profile: "/images/profile/profile1-anonymous.png",
    post1: "Rating: 5/5",
    post2: "Date reviewed: 14-01-2024",
    post3: "𖡡 Malaysia",
  },
  {
    id: 5,
    desc1: "Best price guarantee",
    desc2: "I appreciate the site's best price guarantee, which gave me peace of mind knowing that I got the lowest rate available. However, I did notice that some exclusive deals advertised elsewhere weren't reflected on this site.",
    name: "LOH WEI YANG",
    profile: "/images/profile/profile1-anonymous.png",
    post1: "Rating: 4/5",
    post2: "Date reviewed: 07-02-2024",
    post3: "𖡡 Malaysia",
  },
  {
    id: 6,
    desc1: "Accurate photos and description",
    desc2: "The photos and descriptions of the hotels on the site were accurate representations of what I experienced during my stay. However, in some cases, I noticed that the photos were slightly outdated, and the hotel had undergone renovations since they were taken. amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum. orem ipsum dolor sit amet consectetur adipiscing elit amet consectetur piscing elit amet consectetur adipiscing elit sed et eletum nulla eu placerat felis etiam tincidunt orci lacus id varius dolor fermum sit amet.",
    name: "JAMES LEONG",
    profile: "/images/profile/profile1-anonymous.png",
    post1: "Rating: 4/5",
    post2: "Date reviewed: 26-02-2024",
    post3: "𖡡 Malaysia",
  },
  {
    id: 7,
    desc1: "Transparent Refund Policy",
    desc2: "I had to cancel my booking due to a change in travel plans, and I was impressed by the site's transparent refund policy. The cancellation process was straightforward, and I received a refund to my original payment method within the specified timeframe without any hassle.",
    name: "HEMMENDRA",
    profile: "/images/profile/profile1-anonymous.png",
    post1: "Rating: 5/5",
    post2: "Date reviewed: 12-03-2024",
    post3: "𖡡 Malaysia",
  },
]

export default Tdata
