const Sdata = [
  {
    id: 1,
    title: "Le Quadri Hotel",
    image: "/images/lequadri-1.jpeg",
    desc: "Welcome to LeQuadri Hotel, where luxury meets convenience in the heart of the city. Our chic lobby welcomes you into a world of opulence and refinement, where dedicated staff ensure your every need is met with unparalleled hospitality. Retreat to our meticulously designed rooms and suites, complete with modern amenities and plush furnishings, offering the perfect sanctuary after a day of exploration. Indulge in culinary delights at our exquisite restaurants and bars, serving up tantalizing international cuisine and artisanal cocktails. With our prime location in the city center, easy access to major attractions, business districts, and transportation hubs ensures you're perfectly positioned to uncover all that the city has to offer. Whether traveling for business or leisure, LeQuadri Hotel promises an unforgettable experience with seamless online booking options. Experience the essence of luxury and hospitality at LeQuadri Hotel and elevate your journey to new heights with us.",
    desc2: "LeQuadri Hotel offers a range of meticulously designed rooms and suites to cater to the diverse needs and preferences of our guests. For those seeking ultimate comfort and luxury, our Executive Suites provide spacious accommodations with separate living areas, ideal for both relaxation and productivity. Guests can unwind in style and enjoy premium amenities, including luxurious bedding, spacious bathrooms, and stunning city views. Our Deluxe Rooms offer a perfect blend of comfort and functionality, featuring modern decor and thoughtful amenities to ensure a pleasant stay. With ample space and cozy furnishings, these rooms provide a welcoming retreat for both business and leisure travelers. For guests traveling with families or larger groups, our Family Suites offer the perfect solution. These spacious suites feature multiple bedrooms and living areas, providing ample space for everyone to relax and enjoy their stay. Additionally, we offer accessible rooms designed to accommodate guests with special needs, ensuring a comfortable and hassle-free experience for all. No matter your preference, LeQuadri Hotel provides a range of accommodations to suit every taste and requirement, ensuring a memorable stay for all our guests.",
    paraImage_one: "/images/singlepage/lequadri-2.jpg",
    paraImage_two: "/images/singlepage/lequadri-3.jpeg",
  },
  {
    id: 2,
    title: "Grand Millennium",
    image: "/images/grand-millennium1.jpeg",
    desc: "Welcome to the Grand Millennium Hotel, where luxury, convenience, and sophistication converge in the heart of Kuala Lumpur. Situated in one of the city's most vibrant districts, our hotel stands as a beacon of elegance and hospitality, offering discerning travelers a truly unforgettable experience. From the moment you step into our lavish lobby, you'll be greeted by a fusion of contemporary design and warm Malaysian hospitality. Our meticulously appointed rooms and suites provide a sanctuary of comfort and style, boasting modern amenities and breathtaking views of the city skyline. Whether you're here for business or leisure, our array of dining options, state-of-the-art facilities, and personalized service ensure that every aspect of your stay exceeds expectations. Explore the wonders of Kuala Lumpur with ease, as our hotel is conveniently located near iconic landmarks, shopping destinations, and entertainment venues. Experience the epitome of luxury and hospitality at the Grand Millennium Hotel, where every moment is crafted to perfection.",
    desc2: "The Grand Millennium Hotel in Kuala Lumpur offers a range of luxurious rooms and suites designed to cater to the diverse needs and preferences of our guests. Our Deluxe Rooms provide a spacious and comfortable retreat, featuring modern furnishings and amenities to ensure a relaxing stay. With plush bedding, elegant decor, and panoramic views of the city, these rooms offer a perfect blend of comfort and style. For those seeking extra space and luxury, our Executive Rooms provide an elevated experience with access to exclusive privileges and amenities. Guests can enjoy additional perks such as complimentary breakfast, evening cocktails, and access to the Executive Lounge. For the ultimate indulgence, our Suites offer a truly luxurious retreat with separate living and dining areas, as well as breathtaking views of Kuala Lumpur's skyline. Guests staying in our suites can enjoy VIP treatment and personalized service, ensuring a truly unforgettable stay. Additionally, we offer accessible rooms designed to accommodate guests with special needs, ensuring a comfortable and hassle-free experience for all. No matter your preference, the Grand Millennium Hotel Kuala Lumpur provides an array of accommodation options to suit every traveler's needs, ensuring a memorable and enjoyable stay in the heart of the city.",
    paraImage_one: "/images/singlepage/grand-millennium2.jpeg",
    paraImage_two: "/images/singlepage/grand-millennium3.jpeg",
  },
  {
    id: 3,
    title: "Shangri-la Hotel",
    image: "/images/shangrila1.jpg",
    desc: "Welcome to an oasis of refinement and indulgence in the heart of Kuala Lumpur, where Shangri-La Hotel Kuala Lumpur invites you to experience a world of unparalleled luxury. Nestled amidst the dynamic cityscape, our hotel offers a sanctuary of opulence and sophistication. With elegantly appointed accommodations, award-winning dining experiences, and world-class facilities including an outdoor pool, rejuvenating spa, and state-of-the-art fitness center, every moment spent with us promises to be extraordinary.",
    desc2: "Our commitment to legendary hospitality ensures that your stay is nothing short of perfection, as our dedicated team anticipates your every need with warmth and precision. Whether you're traveling for business or leisure, immerse yourself in the epitome of luxury at Shangri-La Hotel, Kuala Lumpur, where every detail is crafted to exceed your expectations. Indulge in a world where luxury knows no bounds and create memories that will last a lifetime. Experience the extraordinary with us.",
    paraImage_one: "/images/singlepage/shangrila2.jpeg",
    paraImage_two: "/images/singlepage/shangrila3.jpeg",
  },
  {
    id: 4,
    title: "Banyan Tree Hotel",
    image: "/images/banyan-tree1.jpeg",
    desc: "Discover a sanctuary of tranquility amidst the vibrant energy of Kuala Lumpur at Banyan Tree Hotel. Our elegant retreat offers a blend of contemporary luxury and traditional charm, providing guests with an unparalleled experience of comfort and sophistication. From exquisitely designed accommodations to award-winning dining and holistic wellness experiences, every moment at Banyan Tree Hotel is crafted to rejuvenate the body, mind, and soul.",
    sidepara: "Immerse yourself in the epitome of luxury with personalized service and attention to detail that exceeds expectations. Whether you're lounging by the infinity pool, enjoying a gourmet meal, or pampering yourself at the spa, our dedicated team ensures that your stay is nothing short of perfect. Experience the serenity and elegance of Banyan Tree Hotel, where every detail is designed to create unforgettable memories in the heart of Kuala Lumpur.",
    paraImage_one: "/images/singlepage/banyan-tree2.jpeg",
    paraImage_two: "/images/singlepage/banyan-tree3.jpeg",
  },
  {
    id: 5,
    title: "Sleeping Lions Suites",
    image: "/images/sleepinglions1.jpeg",
    desc: "Nestled in Kuala Lumpur's bustling Bukit Bintang district, Sleeping Lion Bukit Bintang offers a serene escape amidst the city's vibrant energy. Our boutique hotel welcomes guests to chic and modern suites, where contemporary comfort meets urban sophistication. Whether lounging by the rooftop pool or indulging in spa treatments, every moment promises relaxation and rejuvenation.",
    sidepara: "At Sleeping Lion Bukit Bintang, our dedicated team ensures personalized hospitality from check-in to check-out. Whether traveling for business or leisure, guests can expect bespoke service and tailored experiences, creating unforgettable memories in the heart of Kuala Lumpur's bustling landscape.",
    paraImage_one: "/images/singlepage/sleepinglions2.jpeg",
    paraImage_two: "/images/singlepage/sleepinglions3.jpeg",
  },
  {
    id: 6,
    title: "Mandarin Oriental",
    image: "/images/mandarinoriental1.jpg",
    desc: "Nestled in the bustling heart of Kuala Lumpur, Mandarin Oriental offers an oasis of luxury and tranquility amidst the vibrant cityscape. With its prime location adjacent to the iconic Petronas Twin Towers, this renowned hotel boasts exquisite accommodations that marry contemporary elegance with timeless sophistication. From spacious rooms and suites with breathtaking views to world-class dining experiences and indulgent spa treatments, every aspect of Mandarin Oriental is designed to elevate your stay to new heights of luxury and comfort.",
    sidepara: "At Mandarin Oriental, Kuala Lumpur, impeccable service is a hallmark of our commitment to excellence. Our dedicated team of hospitality professionals ensures that every guest receives personalized attention and care, from seamless check-in to arranging bespoke experiences tailored to your preferences. Whether you're visiting for business or leisure, immerse yourself in the epitome of luxury and discover unforgettable moments at Mandarin Oriental, Kuala Lumpur.",
    paraImage_one: "/images/singlepage/mandarinoriental2.jpeg",
    paraImage_two: "/images/singlepage/mandarinoriental3.jpeg",
  },
]

export default Sdata
